// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRZrP6K34ZiykoqUO52BpFTh88fL14a8',
    appId: '1:663874707473:web:7ec0ec422b0ff06f19d1b0',
    messagingSenderId: '663874707473',
    projectId: 'lifestyleapp-d76bf',
    authDomain: 'lifestyleapp-d76bf.firebaseapp.com',
    storageBucket: 'lifestyleapp-d76bf.firebasestorage.app',
    measurementId: 'G-3XWM2L0YP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpr5b7eAs5qZarKnW3hkFWxQSUZUGgMk',
    appId: '1:663874707473:android:7c54b1f00ee6ee3c19d1b0',
    messagingSenderId: '663874707473',
    projectId: 'lifestyleapp-d76bf',
    storageBucket: 'lifestyleapp-d76bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCB1mKbOrw-yOG6HH4_NsyMA5exUGauc',
    appId: '1:663874707473:ios:2e28a8c955db9b3719d1b0',
    messagingSenderId: '663874707473',
    projectId: 'lifestyleapp-d76bf',
    storageBucket: 'lifestyleapp-d76bf.firebasestorage.app',
    iosBundleId: 'com.example.lifestyleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLCB1mKbOrw-yOG6HH4_NsyMA5exUGauc',
    appId: '1:663874707473:ios:2e28a8c955db9b3719d1b0',
    messagingSenderId: '663874707473',
    projectId: 'lifestyleapp-d76bf',
    storageBucket: 'lifestyleapp-d76bf.firebasestorage.app',
    iosBundleId: 'com.example.lifestyleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNRZrP6K34ZiykoqUO52BpFTh88fL14a8',
    appId: '1:663874707473:web:5484db3b5beec7fc19d1b0',
    messagingSenderId: '663874707473',
    projectId: 'lifestyleapp-d76bf',
    authDomain: 'lifestyleapp-d76bf.firebaseapp.com',
    storageBucket: 'lifestyleapp-d76bf.firebasestorage.app',
    measurementId: 'G-EY6TFW53KG',
  );
}
